version: '3'
services:
  nginx:
    build:
      dockerfile: ./docker/nginx.dockerfile
      context: .
    image: romario/nginx
    container_name: servidor_nginx
    ports:
      - "80:80"
    networks:
      - alura-network
    depends_on:
      - node1
      - node2
      - node3
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - alura-network
  node1:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: romario/alura-books
    container_name: worker_1
    ports:
      - "3000"
    networks:
      - alura-network
    depends_on:
      - mongodb
  node2:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: romario/alura-books
    container_name: worker_2
    ports:
      - "3000"
    networks:
      - alura-network
    depends_on:
      - mongodb
  node3:
    build:
      dockerfile: ./docker/alura-books.dockerfile
      context: .
    image: romario/alura-books
    container_name: worker_3
    ports:
      - "3000"
    networks:
      - alura-network
    depends_on:
      - mongodb
networks:
  alura-network:
    driver: bridge